services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Keep container-installed deps isolated from host.
      - .:/app # Mount local source code into the container for live reload.
  # Service to run tests
  # No ports needed for tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # Preserve container's node_modules (avoid host overwrite).
      - .:/app # Share project files with test container so test edits are immediate.
    # Overiding the default command inside the dockerfile.dev file.
    command: ["npm", "run", "test"]